version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_manager
    ports:
      - "54321:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data
